# Generated by Django 2.2.2 on 2019-06-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('CRO', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('especialidade', models.CharField(max_length=40)),
            ],
        ),
    ]
