# Generated by Django 2.2.2 on 2019-06-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Dentista',
        ),
        migrations.DeleteModel(
            name='Procedimento',
        ),
    ]
