# Generated by Django 2.2.2 on 2019-06-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='data',
            new_name='dataC',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='hora',
            new_name='horaC',
        ),
    ]
