# Generated by Django 2.2.2 on 2019-06-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_auto_20190621_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='descricao',
        ),
        migrations.AddField(
            model_name='consulta',
            name='preco',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='statusConsulta',
            field=models.CharField(choices=[('realizada', 'Realizada'), ('á ser realizada', 'Á ser realizada'), ('cancelada', 'Cancelada')], default='á ser realizada', max_length=15),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='statusPagamento',
            field=models.CharField(choices=[('pago', 'Confirmado'), ('não pago', 'Não Pago'), ('á ser pago', 'Em andamento')], default='á ser pago', max_length=15),
        ),
    ]
