# Generated by Django 2.2.2 on 2019-06-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_auto_20190622_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
